language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sh -c "composer global require 'phpunit/phpunit=3.7.33'"
  - mkdir ./app/tmp
  - chmod -R 777 ./app/tmp
  - mysql -uroot -e "create database todomanager"
  - mysql -uroot -e "create database test_todomanager"
  - echo "<?php
    class DATABASE_CONFIG {
      public \$default = array(
        'datasource' => 'Database/Mysql',
        'persistent' => false,
        'host' => 'localhost',
        'login' => 'root',
        'password' => '',
        'database' => 'todomanager',
        'prefix' => ''
      );
      public \$test = array(
        'datasource' => 'Database/Mysql',
        'persistent' => false,
        'host' => 'localhost',
        'login' => 'root',
        'password' => '',
        'database' => 'test_todomanager',
        'prefix' => ''
      );
      }" > app/Config/database.php
  - ./app/Console/cake schema create --yes

script:
  - ./app/Console/cake test app All
